django_research/urls.py
# -*- coding: utf-8 -*-
"""プロジェクト全体のURL設定用モジュール。"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^model_sample/', include('model_sample.urls', namespace='model_sample')),
    url(r'^form_sample/', include('form_sample.urls', namespace='form_sample')),
]

# 以下、debug-toolbar用の設定。
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

form_sample/urls.py
# -*- coding: utf-8 -*-
"""このアプリケーションのURL設定用モジュール。"""

from django.conf.urls import url

from form_sample import views

urlpatterns = [
    # ユーザ登録サンプルページ。
    url(r'^registration/$', views.create_user, name='create_user'),
]

model_sample/urls.py
# -*- coding: utf-8 -*-
"""このアプリケーションのURL設定用モジュール。"""

from django.conf.urls import url

from model_sample import views

urlpatterns = [
    # 多対一サンプル
    url(r'^many_to_one/manufacturer_list/$', views.manufacturer_list, name='manufacturer_list'),
    url(r'^many_to_one/car_list/(?P<manufacturer_id>\d+)/$', views.car_list, name='car_list'),

    # 多対多サンプル
    url(r'^many_to_many/article_and_tag_list/$', views.article_and_tag_list, name='article_and_tag_list'),
    url(r'^many_to_many/article_detail/(?P<article_id>\d+)/$', views.article_detail, name='article_detail'),
    url(r'^many_to_many/tag_detail/(?P<tag_id>\d+)/$', views.tag_detail, name='tag_detail'),
]

model_sample/models.py
# -*- coding: utf-8 -*-
u"""モデルクラスをまとめたモジュール。"""

from django.db import models


class Manufacturer(models.Model):
    u"""自動車製造業者を表すモデル。"""

    name = models.CharField(max_length=256)

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return self.name


class Car(models.Model):
    u"""自動車を表すモデル。"""

    name = models.CharField(max_length=256)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return self.name


class Article(models.Model):
    u"""ブログ記事を表すモデル。"""

    title = models.CharField(max_length=256)
    # 今回はサンプルのため、4,000文字程度とする。
    text = models.TextField(max_length=4096)

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return self.title


class Tag(models.Model):
    u"""ブログ記事を分類するタグ。"""

    name = models.CharField(max_length=256)

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return self.name


class ArticleTag(models.Model):
    u"""ArticleモデルとTagモデルの多対多関係を実現する中間テーブル。"""

    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    create_date_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return 'Article:' + self.article.title + ' Tag:' + self.tag.name

model_sample/views.py
# -*- coding: utf-8 -*-
u"""ビューの処理をまとめたモジュール。"""

from django.http import Http404
from django.http import HttpResponse
from django.template import loader

from model_sample.models import Article
from model_sample.models import ArticleTag
from model_sample.models import Manufacturer
from model_sample.models import Tag


def manufacturer_list(request):
    u"""自動車製造業者一覧を表示する。"""
    manufacturers = Manufacturer.objects.all()
    template = loader.get_template('model_sample/manufacturer_list.html')
    context = {
        'manufacturers': manufacturers,
    }
    return HttpResponse(template.render(context, request))


def car_list(request, manufacturer_id):
    u"""特定の業者が製造している、自動車一覧を表示する。"""
    try:
        manufacturer = Manufacturer.objects.get(pk=manufacturer_id)
    except Manufacturer.DoesNotExist:
        raise Http404("Manufacturer does not exist")

    template = loader.get_template('model_sample/car_list.html')
    context = {
        'manufacturer': manufacturer,
    }
    return HttpResponse(template.render(context, request))


def article_and_tag_list(request):
    u"""記事とタグの一覧を表示する。"""
    tags = Tag.objects.all()
    articles = Article.objects.all()

    template = loader.get_template('model_sample/article_and_tag_list.html')
    context = {
        'tags': tags,
        'articles': articles,
    }
    return HttpResponse(template.render(context, request))


def article_detail(request, article_id=None):
    u"""記事の詳細を表示する。"""
    try:
        article = Article.objects.get(pk=article_id)
    except Article.DoesNotExist:
        raise Http404("Article does not exist")

    article_tags = ArticleTag.objects.filter(article=article_id)

    template = loader.get_template('model_sample/article_detail.html')
    context = {
        'article': article,
        'article_tags': article_tags,
    }
    return HttpResponse(template.render(context, request))


def tag_detail(request, tag_id=None):
    u"""タグの詳細を表示する。"""
    try:
        tag = Tag.objects.get(pk=tag_id)
    except Tag.DoesNotExist:
        raise Http404("Tag does not exist")

    article_tags = ArticleTag.objects.filter(tag=tag_id)

    template = loader.get_template('model_sample/tag_detail.html')
    context = {
        'tag': tag,
        'article_tags': article_tags,
    }
    return HttpResponse(template.render(context, request))

model_sample/templates/model_sample/article_and_tag_list.html
{% extends "base.html" %}

{% block title %}Many to many sample{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Many to many sample</h2>
        <ul class="breadcrumb">
            <li>top</li>
        </ul>
    </div>

    <!-- Articleの一覧 -->
    <div class="container">
        <h4>Articles</h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>title</th>
                    <th>text</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <th>{{ article.id }}</th>
                        <th><a href="{% url 'model_sample:article_detail' article_id=article.id %}">{{ article.title }}</a></th>
                        <th>{{ article.text }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Tagの一覧 -->
    <div class="container">
        <h4>Tags</h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                </tr>
            </thead>
            <tbody>
                {% for tag in tags %}
                    <tr>
                        <th>{{ tag.id }}</th>
                        <th><a href="{% url 'model_sample:tag_detail' tag_id=tag.id %}">{{ tag.name }}</a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

model_sample/templates/model_sample/article_detail.html
{% extends "base.html" %}

{% block title %}Many to many sample{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Many to many sample</h2>
        <ul class="breadcrumb">
            <li><a href="{% url 'model_sample:article_and_tag_list' %}">top</a></li>
            <li>article_detail</li>
        </ul>
    </div>

    <div class="container">
        <h4>Title:</h4>
        {{ article.title }}
        <br/>

        <h4>Text:</h4>
        <pre>{{ article.text }}</pre>
        <br/>

        <h4>Tags:</h4>
        {% if article_tags %}
            <ul>
            {% for article_tag in article_tags %}
                <li><a href="{% url 'model_sample:tag_detail' tag_id=article_tag.tag.id %}">{{ article_tag.tag.name }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            empty
        {% endif %}
    </div>
{% endblock content %}

model_sample/templates/model_sample/car_list.html
{% extends "base.html" %}

{% block title %}many to one sample{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Many to one sample</h2>
        <ul class="breadcrumb">
            <li><a href="{% url 'model_sample:manufacturer_list' %}">manufacturer_list</a></li>
            <li>car_list</li>
        </ul>
    </div>

    <div class="container">
        <h4>{{ manufacturer.name }} car list</h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>car_name</th>
                </tr>
            </thead>
            <tbody>
                {% for car in manufacturer.car_set.all %}
                    <tr>
                        <th>{{ car.id }}</th>
                        <th>{{ car.name }}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

model_sample/templates/model_sample/manufacturer_list.html
{% extends "base.html" %}

{% block title %}many to one sample{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Many to one sample</h2>
        <ul class="breadcrumb">
            <li>manufacturer_list</li>
        </ul>
    </div>

    <div class="container">
        <h4>Manufacturer list</h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>manufacturer_name</th>
                </tr>
            </thead>
            <tbody>
                {% for manufacturer in manufacturers %}
                    <tr>
                        <th>{{ manufacturer.id }}</th>
                        <th><a href="{% url 'model_sample:car_list' manufacturer_id=manufacturer.id %}">{{ manufacturer.name }}</a></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

model_sample/templates/model_sample/tag_detail.html
{% extends "base.html" %}

{% block title %}Many to many sample{% endblock title %}

{% block content %}
    <div class="container">
        <h2>Many to many sample</h2>
        <ul class="breadcrumb">
            <li><a href="{% url 'model_sample:article_and_tag_list' %}">top</a></li>
            <li>tag_detail</li>
        </ul>
    </div>

    <div class="container">
        <h4>Tag name:</h4>
        {{ tag.name }}
        <br/>

        <h4>Relate articles:</h4>
        {% if article_tags %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                    </tr>
                </thead>
                <tbody>
                    {% for article_tag in article_tags %}
                        <tr>
                            <th>{{ article_tag.article.id }}</th>
                            <th><a href="{% url 'model_sample:article_detail' article_id=article_tag.article.id %}">
                                {{ article_tag.article.title }}
                            </a></th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            empty
        {% endif %}
    </div>
{% endblock content %}