django_research/urls.py
# -*- coding: utf-8 -*-
"""プロジェクト全体のURL設定用モジュール。"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^model_sample/', include('model_sample.urls', namespace='model_sample')),
    url(r'^form_sample/', include('form_sample.urls', namespace='form_sample')),
]

# 以下、debug-toolbar用の設定。
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

form_sample/urls.py
# -*- coding: utf-8 -*-
"""このアプリケーションのURL設定用モジュール。"""

from django.conf.urls import url

from form_sample import views

urlpatterns = [
    # ユーザ登録サンプルページ。
    url(r'^registration/$', views.create_user, name='create_user'),
]

form_sample/models.py
# -*- coding: utf-8 -*-
u"""モデルクラスをまとめたモジュール。"""

from django.db import models


class User(models.Model):
    u"""ユーザ情報を表すモデル。

    注意:
    実運用上では、Userというモデル名を作るのはナンセンス。
    というのも、Djangoの認証機能において、デフォルトでUserという名称のモデルクラスが用意されているから。
    """

    MALE = 'male'
    FEMALE = 'female'

    email_address = models.EmailField(
        max_length=256,
        help_text='A record determined uniquely by this field.',
        unique=True
    )
    password = models.CharField(
        max_length=256
    )
    first_name = models.CharField(
        max_length=256
    )
    last_name = models.CharField(
        max_length=256
    )
    gender = models.CharField(
        max_length=16,
        help_text='See this module constant.'
    )

    def __str__(self):
        u"""このクラスの文字列表現。"""
        return self.email_address

form_sample/forms.py
# -*- coding: utf-8 -*-
u"""フォームに関するクラスをまとめたモジュール。"""

from django import forms

from form_sample.models import User


class UserForm(forms.Form):
    u"""Userを作成するためのフォーム。"""

    email_address = forms.EmailField(
        label='email:',
        max_length=256,
    )
    password_1 = forms.CharField(
        label='password:',
        max_length=256,
        widget=forms.PasswordInput,
    )
    password_2 = forms.CharField(
        max_length=256,
        widget=forms.PasswordInput,
    )
    first_name = forms.CharField(
        label='first name:',
        max_length=256
    )
    last_name = forms.CharField(
        label='last name:',
        max_length=256
    )
    # ChoiceFieldの概要については、以下URLを参照すること。
    # https://docs.djangoproject.com/ja/1.11/ref/models/fields/#field-choices
    gender = forms.ChoiceField(
        label='gender:',
        widget=forms.Select,
        choices=(
            (User.MALE, 'male'),
            (User.FEMALE, 'female'),
        )
    )

form_sample/views.py
# -*- coding: utf-8 -*-
u"""ビューの処理をまとめたモジュール。"""

from django.shortcuts import render

from form_sample.forms import UserForm
from form_sample.models import User


def create_user(request):
    u"""フォームによる、ユーザレコードの作成を行う。"""
    if request.method == 'POST':
        # POSTによりデータ送信された場合。
        form = UserForm(request.POST)

        # 各種チェックを実施して、駄目ならフォームページへ。
        if not form.is_valid():
            return render(
                request,
                'form_sample/registration_form.html',
                dict(form=form, message='form validation error.'),
            )
        if form.cleaned_data['password_1'] != form.cleaned_data['password_2']:
            return render(
                request,
                'form_sample/registration_form.html',
                dict(form=form, message='incorrect password.'),
            )
        if User.objects.filter(email_address=form.cleaned_data['email_address']).exists():
            return render(
                request,
                'form_sample/registration_form.html',
                dict(form=form, message='user record already exists.'),
            )

        # Userレコードを生成。
        user = User.objects.create(
            email_address=form.cleaned_data['email_address'],
            password=form.cleaned_data['password_1'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            gender=form.cleaned_data['gender'],
        )
        user.save()

        # フォーム入力画面へ遷移。
        return render(
            request,
            'form_sample/registration_completion.html',
            dict(message='registration completed.'),
        )
    else:
        # 空の入力フォームを表示する場合。
        form = UserForm()
        return render(
            request,
            'form_sample/registration_form.html',
            dict(form=form),
        )

form_sample/templates/form_sample/registration_completion.html
{% extends "base.html" %}

{% block title %}regstration completed{% endblock title %}

{% block content %}
    <h2>Registration Completed !</h2>
{% endblock %}

form_sample/templates/form_sample/registration_form.html
{% extends "base.html" %}

{% block title %}regstration form sample{% endblock title %}

{% block content %}
    <div class="container" style="padding: 10px">
        <h2>User Registration Form Sample</h2>
    </div>

    <!--
        注意:
          以下の例では、個々のフォームのプロパティを、直接コーディングしている。
          本来であれば、フォームの描画はもっと楽な方法を取るべきである。
          こうした理由は、今回のサンプルが練習用であることと、
          bootstrapを使う上で、クラス指定が必要であることを考慮したため。

        代案:
        * Widgetクラスを継承して、モデル側でクラスを調整する方法。
          * この方法だと、モデルとテンプレートが密結合になってしまう問題点がある。
        * Django bootstrap formを使う方法。
          * 参考サイトを参照。実運用では、これを使うといいだろう。
    -->

    <!--エラーがあれば、エラーを表示。-->
    {% if message %}
        <p class="bg-danger">{{ message }}</p>
    {% endif %}

    <div class="container" style="padding: 10px">
        <form action="{% url 'form_sample:create_user' %}" method='post' class="form-horizontal" style="margin-bottom:15px">

            <!-- DjangoのCSRF対策で、以下トークンの送信が必要。 -->
            {% csrf_token %}

            <!-- メールアドレス -->
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">
                    {{ form.email_address.label }}
                </label>
                <div class="col-sm-6">
                    <input type="email" name="email_address" id="email" class="form-control">
                </div>
            </div>

            <!-- パスワード -->
            <div class="form-group">
                <label class="control-label col-sm-2">
                    {{ form.password_1.label }}
                </label>
                <div class="col-sm-offset2 col-sm-6">
                    <input type="password" name="password_1" class="form-control" style="margin-bottom:5px">
                    <input type="password" name="password_2" class="form-control" placeholder="confirm your password.">
                </div>
            </div>

            <!-- 氏名 -->
            <div class="form-group">
                <label class="control-label col-sm-2">
                    {{ form.first_name.label }}
                </label>
                <div class="col-sm-6">
                    <input type="text" name="first_name" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">
                    {{ form.last_name.label }}
                </label>
                <div class="col-sm-6">
                    <input type="text" name="last_name" class="form-control">
                </div>
            </div>

            <!-- 性別 -->
            <div class="form-group">
                <label class="control-label col-sm-2">
                    {{ form.gender.label }}
                </label>
                <div class="col-sm-6">
                    <label class="radio-inline"><input type="radio" name="gender" value="male"> male</label>
                    <label class="radio-inline"><input type="radio" name="gender" value="female"> female</label>
                </div>
            </div>

            <!-- 送信ボタン -->
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <button type="submit" class="btn btn-primary">submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}